# Generated by Django 4.1.7 on 2023-03-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_category_options_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phase',
            field=models.CharField(blank=True, choices=[('DFT', 'Draft'), ('SBM', 'Submitted'), ('PUB', 'Published'), ('REJ', 'Rejected'), ('ARC', 'Archived')], default='DFT', max_length=20),
        ),
    ]
